/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author thoma
 */
public class EliminarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form EliminarUsuario
     */
    public EliminarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminarUsuario = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_rut = new javax.swing.JLabel();
        jTextField_rut = new javax.swing.JTextField();
        jSeparator_rut = new javax.swing.JSeparator();
        jLabel_nombre = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jSeparator_nombre = new javax.swing.JSeparator();
        jLabel_correo = new javax.swing.JLabel();
        jTextField_correo = new javax.swing.JTextField();
        jSeparator_correo = new javax.swing.JSeparator();
        jLabel_comuna = new javax.swing.JLabel();
        jTextField_comuna = new javax.swing.JTextField();
        jSeparator_comuna = new javax.swing.JSeparator();
        jLabel_direccion = new javax.swing.JLabel();
        jTextField_direccion = new javax.swing.JTextField();
        jSeparator_direccion = new javax.swing.JSeparator();
        jLabel_telefono = new javax.swing.JLabel();
        jTextField_telefono = new javax.swing.JTextField();
        jSeparator_telefono = new javax.swing.JSeparator();
        jLabel_fNac = new javax.swing.JLabel();
        jTextField_fNac = new javax.swing.JTextField();
        jSeparator_fNac = new javax.swing.JSeparator();
        jPanel_menu = new javax.swing.JPanel();
        jLabel_menu = new javax.swing.JLabel();
        jPanel_registrar = new javax.swing.JPanel();
        jLabel_registrar = new javax.swing.JLabel();

        eliminarUsuario.setBackground(new java.awt.Color(51, 51, 51));
        eliminarUsuario.setForeground(new java.awt.Color(51, 51, 51));
        eliminarUsuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                eliminarUsuarioMouseDragged(evt);
            }
        });
        eliminarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Ingresar Usuario");
        eliminarUsuario.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jLabel_rut.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_rut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_rut.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_rut.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_rut.setText("Rut:");
        eliminarUsuario.add(jLabel_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));

        jTextField_rut.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_rut.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_rut.setText("00.000.000-K");
        jTextField_rut.setBorder(null);
        jTextField_rut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_rutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_rutMouseEntered(evt);
            }
        });
        jTextField_rut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_rutKeyPressed(evt);
            }
        });
        eliminarUsuario.add(jTextField_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 270, -1));
        eliminarUsuario.add(jSeparator_rut, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 270, 10));

        jLabel_nombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_nombre.setText("Nombre:");
        eliminarUsuario.add(jLabel_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 130, -1));

        jTextField_nombre.setEditable(false);
        jTextField_nombre.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_nombre.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_nombre.setBorder(null);
        jTextField_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_nombreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_nombreMouseEntered(evt);
            }
        });
        jTextField_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nombreKeyPressed(evt);
            }
        });
        eliminarUsuario.add(jTextField_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 270, -1));
        eliminarUsuario.add(jSeparator_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 270, 10));

        jLabel_correo.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_correo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_correo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_correo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_correo.setText("Correo:");
        eliminarUsuario.add(jLabel_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, -1));

        jTextField_correo.setEditable(false);
        jTextField_correo.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_correo.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_correo.setBorder(null);
        jTextField_correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_correoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_correoMouseEntered(evt);
            }
        });
        jTextField_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_correoKeyPressed(evt);
            }
        });
        eliminarUsuario.add(jTextField_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 270, -1));
        eliminarUsuario.add(jSeparator_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 270, 10));

        jLabel_comuna.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_comuna.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_comuna.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_comuna.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_comuna.setText("Comuna:");
        eliminarUsuario.add(jLabel_comuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 130, -1));

        jTextField_comuna.setEditable(false);
        jTextField_comuna.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_comuna.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_comuna.setBorder(null);
        jTextField_comuna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_comunaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_comunaMouseEntered(evt);
            }
        });
        jTextField_comuna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_comunaKeyPressed(evt);
            }
        });
        eliminarUsuario.add(jTextField_comuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 270, -1));
        eliminarUsuario.add(jSeparator_comuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 270, 10));

        jLabel_direccion.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_direccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_direccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_direccion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_direccion.setText("Direccion:");
        eliminarUsuario.add(jLabel_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 130, -1));

        jTextField_direccion.setEditable(false);
        jTextField_direccion.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_direccion.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_direccion.setBorder(null);
        jTextField_direccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_direccionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_direccionMouseEntered(evt);
            }
        });
        jTextField_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_direccionKeyPressed(evt);
            }
        });
        eliminarUsuario.add(jTextField_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 270, -1));
        eliminarUsuario.add(jSeparator_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 270, 10));

        jLabel_telefono.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_telefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_telefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_telefono.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_telefono.setText("Telefono:");
        eliminarUsuario.add(jLabel_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 130, -1));

        jTextField_telefono.setEditable(false);
        jTextField_telefono.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_telefono.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_telefono.setBorder(null);
        jTextField_telefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_telefonoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_telefonoMouseEntered(evt);
            }
        });
        jTextField_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_telefonoKeyPressed(evt);
            }
        });
        eliminarUsuario.add(jTextField_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 270, -1));
        eliminarUsuario.add(jSeparator_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 270, 10));

        jLabel_fNac.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_fNac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_fNac.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_fNac.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_fNac.setText("Fecha nacimiento:");
        eliminarUsuario.add(jLabel_fNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, -1));

        jTextField_fNac.setEditable(false);
        jTextField_fNac.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_fNac.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_fNac.setBorder(null);
        jTextField_fNac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_fNacMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_fNacMouseEntered(evt);
            }
        });
        jTextField_fNac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_fNacKeyPressed(evt);
            }
        });
        eliminarUsuario.add(jTextField_fNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 270, -1));
        eliminarUsuario.add(jSeparator_fNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 270, 10));

        jPanel_menu.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_menu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_menu.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_menu.setText("Menu");
        jLabel_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_menuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_menuLayout = new javax.swing.GroupLayout(jPanel_menu);
        jPanel_menu.setLayout(jPanel_menuLayout);
        jPanel_menuLayout.setHorizontalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_menuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_menuLayout.setVerticalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_menuLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        eliminarUsuario.add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jPanel_registrar.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_registrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_registrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_registrar.setText("Eliminar");
        jLabel_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_registrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_registrarLayout = new javax.swing.GroupLayout(jPanel_registrar);
        jPanel_registrar.setLayout(jPanel_registrarLayout);
        jPanel_registrarLayout.setHorizontalGroup(
            jPanel_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_registrarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_registrarLayout.setVerticalGroup(
            jPanel_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(jPanel_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_registrarLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        eliminarUsuario.add(jPanel_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(eliminarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(eliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_rutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_rutMouseClicked

    }//GEN-LAST:event_jTextField_rutMouseClicked

    private void jTextField_rutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_rutMouseEntered
        //BORRAR
    }//GEN-LAST:event_jTextField_rutMouseEntered

    private void jTextField_rutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_rutKeyPressed
        //hacer que con el tab desaparesca ************
        //sino borrar
    }//GEN-LAST:event_jTextField_rutKeyPressed

    private void jTextField_nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_nombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreMouseClicked

    private void jTextField_nombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_nombreMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreMouseEntered

    private void jTextField_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreKeyPressed

    private void jTextField_correoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_correoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_correoMouseClicked

    private void jTextField_correoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_correoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_correoMouseEntered

    private void jTextField_correoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_correoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_correoKeyPressed

    private void jTextField_comunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_comunaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_comunaMouseClicked

    private void jTextField_comunaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_comunaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_comunaMouseEntered

    private void jTextField_comunaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_comunaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_comunaKeyPressed

    private void jTextField_direccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_direccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_direccionMouseClicked

    private void jTextField_direccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_direccionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_direccionMouseEntered

    private void jTextField_direccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_direccionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_direccionKeyPressed

    private void jTextField_telefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_telefonoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telefonoMouseClicked

    private void jTextField_telefonoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_telefonoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telefonoMouseEntered

    private void jTextField_telefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telefonoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telefonoKeyPressed

    private void jTextField_fNacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_fNacMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fNacMouseClicked

    private void jTextField_fNacMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_fNacMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fNacMouseEntered

    private void jTextField_fNacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_fNacKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fNacKeyPressed

    private void jLabel_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_menuMouseClicked
        Menu menu = new Menu();
        menu.setSize(660, 460);
        menu.setLocation(0,0);

        eliminarUsuario.removeAll();
        eliminarUsuario.add(menu,new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,-1,-1));
        eliminarUsuario.revalidate();
        eliminarUsuario.repaint();
    }//GEN-LAST:event_jLabel_menuMouseClicked

    private void jLabel_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registrarMouseClicked
        //Eliminar el usuario
    }//GEN-LAST:event_jLabel_registrarMouseClicked

    private void eliminarUsuarioMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarUsuarioMouseDragged
        //BORRAR
    }//GEN-LAST:event_eliminarUsuarioMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel eliminarUsuario;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_comuna;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_direccion;
    private javax.swing.JLabel jLabel_fNac;
    private javax.swing.JLabel jLabel_menu;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_registrar;
    private javax.swing.JLabel jLabel_rut;
    private javax.swing.JLabel jLabel_telefono;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JPanel jPanel_registrar;
    private javax.swing.JSeparator jSeparator_comuna;
    private javax.swing.JSeparator jSeparator_correo;
    private javax.swing.JSeparator jSeparator_direccion;
    private javax.swing.JSeparator jSeparator_fNac;
    private javax.swing.JSeparator jSeparator_nombre;
    private javax.swing.JSeparator jSeparator_rut;
    private javax.swing.JSeparator jSeparator_telefono;
    private javax.swing.JTextField jTextField_comuna;
    private javax.swing.JTextField jTextField_correo;
    private javax.swing.JTextField jTextField_direccion;
    private javax.swing.JTextField jTextField_fNac;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_rut;
    private javax.swing.JTextField jTextField_telefono;
    // End of variables declaration//GEN-END:variables
}
