/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Impl_prueba;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author thoma
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int xMouse;
    int yMouse;
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel_interaccion = new javax.swing.JPanel();
        jPanel_header = new javax.swing.JPanel();
        jPanel_salir = new javax.swing.JPanel();
        jLabel_salir = new javax.swing.JLabel();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_usuario = new javax.swing.JLabel();
        jTextField_usuario = new javax.swing.JTextField();
        jSeparator_usuario = new javax.swing.JSeparator();
        jLabel_contraseña = new javax.swing.JLabel();
        jPasswordField_contraseña = new javax.swing.JPasswordField();
        jSeparator_contraseña = new javax.swing.JSeparator();
        jPanel_entrar = new javax.swing.JPanel();
        jLabel_Acceder = new javax.swing.JLabel();
        jPanel_diseño = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        nombre_empresa = new javax.swing.JLabel();
        wallpaper1 = new javax.swing.JLabel();
        wallpaper2 = new javax.swing.JLabel();
        wallpaper3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel_interaccion.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_interaccion.setForeground(new java.awt.Color(51, 51, 51));
        jPanel_interaccion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_interaccionMouseDragged(evt);
            }
        });
        jPanel_interaccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_header.setBackground(new java.awt.Color(0, 0, 0));
        jPanel_header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel_header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel_headerMouseDragged(evt);
            }
        });
        jPanel_header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_headerMouseEntered(evt);
            }
        });

        jPanel_salir.setBackground(new java.awt.Color(0, 0, 0));

        jLabel_salir.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_salir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_salir.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_salir.setText("X");
        jLabel_salir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jLabel_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_salirLayout = new javax.swing.GroupLayout(jPanel_salir);
        jPanel_salir.setLayout(jPanel_salirLayout);
        jPanel_salirLayout.setHorizontalGroup(
            jPanel_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        jPanel_salirLayout.setVerticalGroup(
            jPanel_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_salirLayout.createSequentialGroup()
                .addComponent(jLabel_salir)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_headerLayout = new javax.swing.GroupLayout(jPanel_header);
        jPanel_header.setLayout(jPanel_headerLayout);
        jPanel_headerLayout.setHorizontalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_headerLayout.setVerticalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addComponent(jPanel_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel_interaccion.add(jPanel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 510));

        jLabel_Titulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("INICIAR SESIÓN");
        jPanel_interaccion.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 124, -1, -1));

        jLabel_usuario.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_usuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_usuario.setText("USUARIO");
        jPanel_interaccion.add(jLabel_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 167, -1, -1));

        jTextField_usuario.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_usuario.setForeground(new java.awt.Color(102, 102, 102));
        jTextField_usuario.setBorder(null);
        jTextField_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_usuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField_usuarioMouseEntered(evt);
            }
        });
        jTextField_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_usuarioKeyPressed(evt);
            }
        });
        jPanel_interaccion.add(jTextField_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 193, 270, -1));
        jPanel_interaccion.add(jSeparator_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 209, 270, 10));

        jLabel_contraseña.setBackground(new java.awt.Color(51, 51, 51));
        jLabel_contraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_contraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_contraseña.setText("CONTRASEÑA");
        jPanel_interaccion.add(jLabel_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 225, -1, -1));

        jPasswordField_contraseña.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField_contraseña.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField_contraseña.setText("************");
        jPasswordField_contraseña.setBorder(null);
        jPasswordField_contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_contraseñaMouseClicked(evt);
            }
        });
        jPasswordField_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_contraseñaActionPerformed(evt);
            }
        });
        jPasswordField_contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_contraseñaKeyPressed(evt);
            }
        });
        jPanel_interaccion.add(jPasswordField_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 251, 270, -1));
        jPanel_interaccion.add(jSeparator_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 267, 270, 10));

        jPanel_entrar.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_Acceder.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_Acceder.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Acceder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Acceder.setText("Acceder");
        jLabel_Acceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AccederMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_entrarLayout = new javax.swing.GroupLayout(jPanel_entrar);
        jPanel_entrar.setLayout(jPanel_entrarLayout);
        jPanel_entrarLayout.setHorizontalGroup(
            jPanel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Acceder, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel_entrarLayout.setVerticalGroup(
            jPanel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Acceder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel_interaccion.add(jPanel_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 283, -1, -1));

        jPanel_diseño.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel_diseño.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        nombre_empresa.setFont(new java.awt.Font("Algerian", 0, 30)); // NOI18N
        nombre_empresa.setForeground(new java.awt.Color(51, 239, 248));
        nombre_empresa.setText("NEXTWIIUBOX");
        jPanel_diseño.add(nombre_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        wallpaper1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpaper.png"))); // NOI18N
        jPanel_diseño.add(wallpaper1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        wallpaper2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpaper.png"))); // NOI18N
        jPanel_diseño.add(wallpaper2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        wallpaper3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpaper.png"))); // NOI18N
        jPanel_diseño.add(wallpaper3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_interaccion, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_diseño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_diseño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_interaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_contraseñaActionPerformed
        //BORRAR
    }//GEN-LAST:event_jPasswordField_contraseñaActionPerformed

    private void jLabel_AccederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AccederMouseClicked
        String usuario = jTextField_usuario.getText();
        String contraseña = jPasswordField_contraseña.getText();
        try {
            boolean existe = new Impl_prueba().login(usuario, contraseña);
            if(existe){
                new Menu().setVisible(true);
                dispose();
            }else{
                 JOptionPane.showMessageDialog(null,"False");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jLabel_AccederMouseClicked

    private void jPanel_interaccionMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_interaccionMouseDragged
        //BORRAR
    }//GEN-LAST:event_jPanel_interaccionMouseDragged

    private void jTextField_usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usuarioMouseEntered
        //BORRAR
    }//GEN-LAST:event_jTextField_usuarioMouseEntered

    private void jPasswordField_contraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_contraseñaMouseClicked
        if(jPasswordField_contraseña.getText().equals("************")){
            jPasswordField_contraseña.setText("");
            jPasswordField_contraseña.setForeground(new Color(204,204,204));
        }
        if(jTextField_usuario.getText().isEmpty()){
            jTextField_usuario.setText("ingrese su correo");
            jTextField_usuario.setForeground(new Color(102,120,102));
        }
    }//GEN-LAST:event_jPasswordField_contraseñaMouseClicked

    private void jTextField_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usuarioMouseClicked
        if(jTextField_usuario.getText().equals("ingrese su correo")){
            jTextField_usuario.setText("");
            jTextField_usuario.setForeground(new Color(204,204,204));
        }
        if(jPasswordField_contraseña.getText().isEmpty()){
            jPasswordField_contraseña.setText("************");
            jPasswordField_contraseña.setForeground(new Color(102,120,102));
        }
    }//GEN-LAST:event_jTextField_usuarioMouseClicked

    private void jPasswordField_contraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_contraseñaKeyPressed
        //MODIFICAR
        //ver si existe el usuario en el sistema

        if(evt.getKeyCode()==10){
            new Menu().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jPasswordField_contraseñaKeyPressed

    private void jTextField_usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usuarioKeyPressed
        //hacer que con el tab desaparesca ************
        //sino borrar
    }//GEN-LAST:event_jTextField_usuarioKeyPressed

    private void jLabel_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_salirMouseClicked

    private void jLabel_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salirMouseEntered
        jPanel_salir.setBackground(Color.red);
    }//GEN-LAST:event_jLabel_salirMouseEntered

    private void jLabel_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_salirMouseExited
        jPanel_salir.setBackground(Color.black);
    }//GEN-LAST:event_jLabel_salirMouseExited

    private void jPanel_headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel_headerMouseDragged

    private void jPanel_headerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_headerMouseEntered
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel_headerMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Acceder;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_contraseña;
    private javax.swing.JLabel jLabel_salir;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JPanel jPanel_diseño;
    private javax.swing.JPanel jPanel_entrar;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JPanel jPanel_interaccion;
    private javax.swing.JPanel jPanel_salir;
    private javax.swing.JPasswordField jPasswordField_contraseña;
    private javax.swing.JSeparator jSeparator_contraseña;
    private javax.swing.JSeparator jSeparator_usuario;
    private javax.swing.JTextField jTextField_usuario;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nombre_empresa;
    private javax.swing.JLabel wallpaper1;
    private javax.swing.JLabel wallpaper2;
    private javax.swing.JLabel wallpaper3;
    // End of variables declaration//GEN-END:variables
}